# Numpy 


In [2]:
import numpy as np 


In [3]:
#1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення
array = np.arange(1,21)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
#2 Створіть двовимірний масив (матрицю) розміром 4x4 заповніть його одиницями та виведіть значення
array = np.ones((4, 4), dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [21]:
#3 створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від -1 до 1 та виведіть його значення
array = np.random.randint(-1, 2, (5, 5))
print(array)

[[-1  1  0  0  0]
 [-1  0  0  0  0]
 [-1  0  0 -1  1]
 [ 1  1  1 -1 -1]
 [ 1  1 -1 -1  0]]


In [19]:
#4 створіть масив розміром 3х3, заповніть його випадковими цілими числами в діапазоні від 0 до 1 та виведіть його значення
array = np.random.randint(0, 2,(3,3))
print(array)

[[1 0 1]
 [0 1 0]
 [1 1 0]]


In [10]:
#5 створіть два одновимірні масиви розміром 6, заповніть його випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення
array1 = np.random.randint(1, 21, size=6)
array2 = np.random.randint(1, 21, size=6)
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)

[18 21 18 24 14 23]
[ -2 -17  14   8  10  -9]
[ 80  38  32 128  24 112]


In [11]:
#6 створіть дві матриці розміром 3х2 та 2х4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою
matrix1 = np.random.randint(1, 6, (3, 2))
matrix2 = np.random.randint(1, 6, (2, 4))
print(np.dot(matrix1, matrix2))

[[ 9 14 11 11]
 [11 22 13 17]
 [17 35 20 27]]


In [12]:
#7 створіть матрицю розміром 3х3 заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її 
matrix = np.random.random((3, 3))
print(matrix.T)

[[0.19755886 0.62257731 0.97426828]
 [0.30227078 0.97395099 0.1232741 ]
 [0.07491173 0.12364883 0.25651654]]


In [25]:
 #8 створіть дві матиці розміром 3х3,заповніть їх випадковими дійсними числами в діапазоні від 1 до 10 та знайдіть їхню різницю 
matrix1 = np.random.uniform(1, 11, (3, 3))
matrix2 = np.random.uniform(1, 11, (3, 3))
print(matrix1 - matrix2)

[[ 2.61397871  0.78337186  5.16410161]
 [ 6.24829336 -2.67532491 -2.94448108]
 [ 1.30911436 -5.87702215  3.02015139]]


In [27]:
#9 створіть дві матиці розміром 3х3,заповніть їх випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть їх добуток
matrix1 = np.random.uniform(-5, 6, (3, 3))
matrix2 = np.random.uniform(-5, 6, (3, 3))
print(np.dot(matrix1, matrix2))

[[ 13.46030911 -26.15253023  10.39690795]
 [-16.77948891  11.042193   -17.86063974]
 [  0.43442924 -21.54895678  -4.22858546]]


# Pandas

In [51]:
import pandas as pd
import numpy as np
url = ("https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%B2_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%96")
data = pd.read_html(url, header=0)[20]
print(data)

                       регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101  

In [30]:
#1 Відобразити перші 10 рядків таблиці за допомогою методу head 
data.head(10)

регіон   1950   1960   1970  1990  1992  1994  1996  \
0  Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1          Вінницька область  224.0  192.0  142.0   124   119   107   103   
2          Волинська область  247.0  250.0  179.0   153   150   137   125   
3   Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4           Донецька область  271.0  214.0  140.0   109    94    82    70   
5        Житомирська область  261.0  223.0  159.0   129   128   118   108   
6       Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7         Запорізька область  219.0  197.0  150.0   124   107    92    81   
8  Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9           Київська область  204.0  189.0  156.0   123   111    99    92   

   2000  2004  2008  2012   2014  
0    73    90   119   126    NaN  
1    84    90   108   112  109.0  
2   112   119   148   148  141.0  
3    71    89   110   112  111.0  
4    61    76    98    98   82.0  
5    89    98   113   122  120.0  
6   115   124   147   151  146.0  
7    71    85   103   106  106.0  
8   103   107   123   124  122.0  
9    73    90   117   122  121.0

In [31]:
#2 Визначити кількість рядків і стовпців в датафрейме (метод shape) 
data.shape

(28, 13)

In [34]:
#3 Замініть значення "—" в таблиці значеннями NaN 
data.replace("—", np.nan)

регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101    84    72   
12          Львівська область  234.0  240.0  171.0   140   132   117   111   
13       Миколаївська область  211.0  194.0  155.0   137   123   107    96   
14            Одеська область  241.0  192.0  148.0   126   114   100    92   
15         Полтавська область  186.0  163.0  131.0   118   108    95    88   
16         Рівненська область  269.0  267.0  193.0   158   154   145   132   
17            Сумська область  216.0  184.0  132.0   115   105    92    84   
18      Тернопільська область  213.0  216.0  157.0   142   138   123   115   
19         Харківська область  197.0  173.0  140.0   114    98    83    76   
20         Херсонська область  208.0  214.0  166.0   143   130   111    98   
21        Хмельницька область  234.0  198.0  148.0   129   124   111   106   
22          Черкаська область  205.0  179.0  144.0   123   114   100    93   
23        Чернівецька область  247.0  218.0  170.0   148   140   128   121   
24       Чернігівська область  220.0  183.0  127.0   108    98    88    82   
25                       Київ    NaN  174.0  159.0   120    97    81    76   
26    Севастополь (міськрада)    NaN    NaN    NaN   125    96    76    69   
27                    Україна  228.0  205.0  152.0   126   114   100    92   

    2000  2004  2008  2012   2014  
0     73    90   119   126    NaN  
1     84    90   108   112  109.0  
2    112   119   148   148  141.0  
3     71    89   110   112  111.0  
4     61    76    98    98   82.0  
5     89    98   113   122  120.0  
6    115   124   147   151  146.0  
7     71    85   103   106  106.0  
8    103   107   123   124  122.0  
9     73    90   117   122  121.0  
10    79    86   102   110  108.0  
11    62    73    95    96   51.0  
12    91   101   113   119  119.0  
13    80    90   112   115  112.0  
14    80    96   120   127  123.0  
15    70    75    97    99  100.0  
16   118   125   148   159  148.0  
17    70    72    91    97   92.0  
18    92    99   113   113  109.0  
19    68    80    98    99  101.0  
20    85    91   113   117  115.0  
21    85    91   110   113  112.0  
22    75    77    95   100   98.0  
23   101   106   122   128  129.0  
24    69    75    89    94   90.0  
25    73    98   116   120  121.0  
26    70    97   110   120    NaN  
27    78    90   110   114  108.0

In [33]:
#4 Визначте типи всіх стовпців за допомогою dataframe.dtypes 
data.dtypes

регіон     object
1950      float64
1960      float64
1970      float64
1990        int64
1992        int64
1994        int64
1996        int64
2000        int64
2004        int64
2008        int64
2012        int64
2014      float64
dtype: object

In [35]:
#5 Замініть типи нечислових стовпців числовими стовпцями. Це стовпці, у яких було розташовано символ "—" 
data.replace("—", np.nan)

регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101    84    72   
12          Львівська область  234.0  240.0  171.0   140   132   117   111   
13       Миколаївська область  211.0  194.0  155.0   137   123   107    96   
14            Одеська область  241.0  192.0  148.0   126   114   100    92   
15         Полтавська область  186.0  163.0  131.0   118   108    95    88   
16         Рівненська область  269.0  267.0  193.0   158   154   145   132   
17            Сумська область  216.0  184.0  132.0   115   105    92    84   
18      Тернопільська область  213.0  216.0  157.0   142   138   123   115   
19         Харківська область  197.0  173.0  140.0   114    98    83    76   
20         Херсонська область  208.0  214.0  166.0   143   130   111    98   
21        Хмельницька область  234.0  198.0  148.0   129   124   111   106   
22          Черкаська область  205.0  179.0  144.0   123   114   100    93   
23        Чернівецька область  247.0  218.0  170.0   148   140   128   121   
24       Чернігівська область  220.0  183.0  127.0   108    98    88    82   
25                       Київ    NaN  174.0  159.0   120    97    81    76   
26    Севастополь (міськрада)    NaN    NaN    NaN   125    96    76    69   
27                    Україна  228.0  205.0  152.0   126   114   100    92   

    2000  2004  2008  2012   2014  
0     73    90   119   126    NaN  
1     84    90   108   112  109.0  
2    112   119   148   148  141.0  
3     71    89   110   112  111.0  
4     61    76    98    98   82.0  
5     89    98   113   122  120.0  
6    115   124   147   151  146.0  
7     71    85   103   106  106.0  
8    103   107   123   124  122.0  
9     73    90   117   122  121.0  
10    79    86   102   110  108.0  
11    62    73    95    96   51.0  
12    91   101   113   119  119.0  
13    80    90   112   115  112.0  
14    80    96   120   127  123.0  
15    70    75    97    99  100.0  
16   118   125   148   159  148.0  
17    70    72    91    97   92.0  
18    92    99   113   113  109.0  
19    68    80    98    99  101.0  
20    85    91   113   117  115.0  
21    85    91   110   113  112.0  
22    75    77    95   100   98.0  
23   101   106   122   128  129.0  
24    69    75    89    94   90.0  
25    73    98   116   120  121.0  
26    70    97   110   120    NaN  
27    78    90   110   114  108.0

In [36]:
#6 Обчислити, скільки проміжків у кожному стовпці (використовуйте методи isnull, sum та len) 
data.isnull().sum()

регіон    0
1950      2
1960      1
1970      1
1990      0
1992      0
1994      0
1996      0
2000      0
2004      0
2008      0
2012      0
2014      2
dtype: int64

In [53]:
# 7 Видалити дані для всієї країни з таблиці в останньому рядку таблиці 
data.drop([27])

регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101    84    72   
12          Львівська область  234.0  240.0  171.0   140   132   117   111   
13       Миколаївська область  211.0  194.0  155.0   137   123   107    96   
14            Одеська область  241.0  192.0  148.0   126   114   100    92   
15         Полтавська область  186.0  163.0  131.0   118   108    95    88   
16         Рівненська область  269.0  267.0  193.0   158   154   145   132   
17            Сумська область  216.0  184.0  132.0   115   105    92    84   
18      Тернопільська область  213.0  216.0  157.0   142   138   123   115   
19         Харківська область  197.0  173.0  140.0   114    98    83    76   
20         Херсонська область  208.0  214.0  166.0   143   130   111    98   
21        Хмельницька область  234.0  198.0  148.0   129   124   111   106   
22          Черкаська область  205.0  179.0  144.0   123   114   100    93   
23        Чернівецька область  247.0  218.0  170.0   148   140   128   121   
24       Чернігівська область  220.0  183.0  127.0   108    98    88    82   
25                       Київ    NaN  174.0  159.0   120    97    81    76   
26    Севастополь (міськрада)    NaN    NaN    NaN   125    96    76    69   

    2000  2004  2008  2012   2014  
0     73    90   119   126    NaN  
1     84    90   108   112  109.0  
2    112   119   148   148  141.0  
3     71    89   110   112  111.0  
4     61    76    98    98   82.0  
5     89    98   113   122  120.0  
6    115   124   147   151  146.0  
7     71    85   103   106  106.0  
8    103   107   123   124  122.0  
9     73    90   117   122  121.0  
10    79    86   102   110  108.0  
11    62    73    95    96   51.0  
12    91   101   113   119  119.0  
13    80    90   112   115  112.0  
14    80    96   120   127  123.0  
15    70    75    97    99  100.0  
16   118   125   148   159  148.0  
17    70    72    91    97   92.0  
18    92    99   113   113  109.0  
19    68    80    98    99  101.0  
20    85    91   113   117  115.0  
21    85    91   110   113  112.0  
22    75    77    95   100   98.0  
23   101   106   122   128  129.0  
24    69    75    89    94   90.0  
25    73    98   116   120  121.0  
26    70    97   110   120    NaN

In [56]:
#8 Замінити пропущені дані у стовпцях середніми значеннями за стовпчиком  (метод fillna)
data.fillna(data.mean())


регіон   1950   1960   1970  1990  1992  1994  1996  \
0   Автономна Республіка Крим  230.0  206.0  160.0   130   109    93    80   
1           Вінницька область  224.0  192.0  142.0   124   119   107   103   
2           Волинська область  247.0  250.0  179.0   153   150   137   125   
3    Дніпропетровська область  204.0  204.0  151.0   123   106    92    80   
4            Донецька область  271.0  214.0  140.0   109    94    82    70   
5         Житомирська область  261.0  223.0  159.0   129   128   118   108   
6        Закарпатська область  314.0  273.0  207.0   168   161   138   128   
7          Запорізька область  219.0  197.0  150.0   124   107    92    81   
8   Івано-Франківська область  243.0  248.0  182.0   155   144   131   122   
9            Київська область  204.0  189.0  156.0   123   111    99    92   
10     Кіровоградська область  216.0  171.0  145.0   126   119   107    96   
11          Луганська область  262.0  235.0  144.0   116   101    84    72   
12          Львівська область  234.0  240.0  171.0   140   132   117   111   
13       Миколаївська область  211.0  194.0  155.0   137   123   107    96   
14            Одеська область  241.0  192.0  148.0   126   114   100    92   
15         Полтавська область  186.0  163.0  131.0   118   108    95    88   
16         Рівненська область  269.0  267.0  193.0   158   154   145   132   
17            Сумська область  216.0  184.0  132.0   115   105    92    84   
18      Тернопільська область  213.0  216.0  157.0   142   138   123   115   
19         Харківська область  197.0  173.0  140.0   114    98    83    76   
20         Херсонська область  208.0  214.0  166.0   143   130   111    98   
21        Хмельницька область  234.0  198.0  148.0   129   124   111   106   
22          Черкаська область  205.0  179.0  144.0   123   114   100    93   
23        Чернівецька область  247.0  218.0  170.0   148   140   128   121   
24       Чернігівська область  220.0  183.0  127.0   108    98    88    82   
25                       Київ    NaN  174.0  159.0   120    97    81    76   
26    Севастополь (міськрада)    NaN    NaN    NaN   125    96    76    69   
27                    Україна  228.0  205.0  152.0   126   114   100    92   

    2000  2004  2008  2012   2014  
0     73    90   119   126    NaN  
1     84    90   108   112  109.0  
2    112   119   148   148  141.0  
3     71    89   110   112  111.0  
4     61    76    98    98   82.0  
5     89    98   113   122  120.0  
6    115   124   147   151  146.0  
7     71    85   103   106  106.0  
8    103   107   123   124  122.0  
9     73    90   117   122  121.0  
10    79    86   102   110  108.0  
11    62    73    95    96   51.0  
12    91   101   113   119  119.0  
13    80    90   112   115  112.0  
14    80    96   120   127  123.0  
15    70    75    97    99  100.0  
16   118   125   148   159  148.0  
17    70    72    91    97   92.0  
18    92    99   113   113  109.0  
19    68    80    98    99  101.0  
20    85    91   113   117  115.0  
21    85    91   110   113  112.0  
22    75    77    95   100   98.0  
23   101   106   122   128  129.0  
24    69    75    89    94   90.0  
25    73    98   116   120  121.0  
26    70    97   110   120    NaN  
27    78    90   110   114  108.0

In [60]:
#9 Отримайте список регіонів, де народжуваність у 2014 році була вищою за середню по Україні 
data2014 = data[data["2014"] > data["2014"].mean()]
data2014[["регіон", "2014"]]

регіон   2014
2           Волинська область  141.0
5         Житомирська область  120.0
6        Закарпатська область  146.0
8   Івано-Франківська область  122.0
9            Київська область  121.0
12          Львівська область  119.0
13       Миколаївська область  112.0
14            Одеська область  123.0
16         Рівненська область  148.0
20         Херсонська область  115.0
21        Хмельницька область  112.0
23        Чернівецька область  129.0
25                       Київ  121.0

In [62]:
#10 В якому регіоні була найвища народжуваність у 2010 та 2012 роках (окремо). 
data2012 = data.sort_values(by = "2012", ascending=False)
data2012[["регіон", "2012"]]

регіон  2012
16         Рівненська область   159
6        Закарпатська область   151
2           Волинська область   148
23        Чернівецька область   128
14            Одеська область   127
0   Автономна Республіка Крим   126
8   Івано-Франківська область   124
5         Житомирська область   122
9            Київська область   122
26    Севастополь (міськрада)   120
25                       Київ   120
12          Львівська область   119
20         Херсонська область   117
13       Миколаївська область   115
27                    Україна   114
18      Тернопільська область   113
21        Хмельницька область   113
1           Вінницька область   112
3    Дніпропетровська область   112
10     Кіровоградська область   110
7          Запорізька область   106
22          Черкаська область   100
15         Полтавська область    99
19         Харківська область    99
4            Донецька область    98
17            Сумська область    97
11          Луганська область    96
24       Чернігівська область    94

In [ ]:
#11 Побудуйте стовпчасту народжуваності за регіонами у 2014 році 
data_plot = data_d.plot.bar(x="регіон", y="2014", rot=90, figsize=(15, 10), fontsize=18)